### ISSUE TITLE
How to integrate an external axis?

### ISSUE THREAD

**Issue by AndyZe** [PickNikRobotics/abb_ros2#2]
We are interested in integrating an external axis (aka MultiMove). I did some reading at the old [ROS1 driver](https://github.com/ros-industrial/abb_robot_driver) and learned a few things:

- The `abb_rws_state_publisher` package publishes the JointState and SystemState, including external axis info.
- `abb_egm_hardware_interface` provides actual control of the axes. It has one EGM channel per "mechanical unit group."

Question:  there's a note saying `abb_egm_hardware_interface` relies on `abb_rws_service_provider`. Is that a hard requirement or something we could avoid?

Related:  https://github.com/ros-industrial/abb_libegm/issues/57

**Comment by AndyZe** [comment]
Maybe @dignakov @gavanderhoorn or @jbeck28 have suggestions

**Comment by AndyZe** [comment]
To me, it looks like the bare minimum to port is `abb_egm_hardware_interface`. The other packages do not seem necessary. I see that `egm_hardware_interface` supports multimove, e.g. [here](https://github.com/ros-industrial/abb_robot_driver/blob/32eb0f48abfd3358cb5a4f3f043f1306a9811b24/abb_egm_hardware_interface/src/egm_hardware_interface.cpp#L478).

**Comment by gavanderhoorn** [comment]
`abb_egm_hardware_interface` already supports multiple mechanical units.

`abb_rws_service_provider` provides services which are used to interrogate the controller at runtime and are used by the hw interface to construct the corresponding `ros_control` resources, and services used to coordinate the RAPID side of the driver (start + stop EGM, configure settings, etc).

As a bare minimum, you could implement a simple node which offers a service which returns a hard-coded configuration (like in https://github.com/ros-industrial/abb_robot_driver/issues/33#issuecomment-932268546 fi).
