### ISSUE TITLE
abb_ros2 colcon build fails in ROS2 Foxy

### ISSUE THREAD

**Issue by MikelBueno** [PickNikRobotics/abb_ros2#24]
Hi, 
First of all, thank you very much for developing a ROS2 driver for ABB Robots.

I am planning to control an ABB IRB120 robot using ROS2.0 Foxy. I have followed the instructions [here](https://github.com/PickNikRobotics/abb_ros2/blob/rolling/docs/README.md), and I receive the following errors (please see the 2 pictures attached) when executing the last _COLCON BUILD_ in my ~/dev_ws workspace (the error is generated when building the abb_hardware_interface package).

![ROS2Foxy - abb_ros2 build failed (I)](https://user-images.githubusercontent.com/98389310/173583070-6571e397-131e-43d5-bf30-20b8808c7d40.png)

![ROS2Foxy - abb_ros2 build failed (II)](https://user-images.githubusercontent.com/98389310/173583096-754c0a56-201e-4c96-957d-5c3342d46f99.png)

Is it because there is not a version for ROS2.0 Foxy released yet, or is it a problem related to my workspace/PC?

Thank you very much in advance!
Regards,
Mikel

**Comment by Tukora** [comment]
Exactly the same for me with ROS2 Foxy.

**Comment by erenguldal** [comment]
Hello, same issue for me with ROS2 Foxy.

**Comment by gbartyzel** [comment]
This package is working with Humble version of `ros2_control` / `ros2_controllers`. So, to be able to run this with Foxy try to build those packages from sources. I've managed to run this in such a way under Galactic distro.

But, first build `ros2_control` and `ros2_controllers` and then `abb_ros2`.

**Comment by erenguldal** [comment]
> This package is working with Humble version of `ros2_control` / `ros2_controllers`. So, to be able to run this with Foxy try to build those packages from sources. I've managed to run this in such a way under Galactic distro.
> 
> But, first build `ros2_control` and `ros2_controllers` and then `abb_ros2`.

Hi, thanks for your respond. I successfully built the Humble version of the ros2_control package, but I couldn't find the Humble version of the ros2_controllers package. I think only foxy rolling and galactic versions are available in this github repo. [https://github.com/ros-controls/ros2_controllers](url) Any idea where I can get it for Humble? Thank you.

**Comment by gbartyzel** [comment]
@erenguldal Just checkout to rolling version.

**Comment by MikelBueno** [comment]
Hi @gbartyzel, thank you very much for your help :) 
The problem with ROS2 Foxy is that ros2_control and ros2_controllers slightly change from Foxy to Rolling/Humble, that is why abb_ros would not build/work in Foxy... Anyway, I have installed ROS2 Rolling and abb_ros2 works, thanks!

**Comment by stephanie-eng** [comment]
Yes, there were some changes to ros2 control that prevent this from working on Foxy. I will try to create a foxy branch.

**Comment by stephanie-eng** [comment]
It sounds like you've got the setup working on Rolling now, but I've also created a Foxy branch to address this in the future!

**Comment by MikelBueno** [comment]
It sounds great @stephanie-eng , thank you very much! :)
