### ISSUE TITLE
Commit 6935658 issue with no controllers  in list

### ISSUE THREAD

**Issue by jodle001** [PickNikRobotics/abb_ros2#58]
@Yadunund I am unable to get the controller to be recognized with this change if I do a fresh install.  Am I doing something wrong that you can tell?

See below and it says that it says that there are zero controllers in the list.  If I revert this commit, it works as normal.

![24jsXgS](https://github.com/PickNikRobotics/abb_ros2/assets/60989139/759fb420-93aa-4a8c-938d-bfea223d457c)

**Comment by jodle001** [comment]
6935658e4944c7ff58067339aca4d0673297018f this commit

**Comment by Yadunund** [comment]
Could you provide more information:
* OS, version of ROS 2 (whether binary or source install)
* versions of moveit2, joint_trajectory_controller
* what launch commands you used
This would help reproduce the behavior. It would also help if you could paste your entire terminal input into a gist and share the link.

**Comment by jodle001** [comment]
- Ubuntu 22 ROS2 Hubmle Binary install
- updated moveit2 binaries.
- I'm using the commands pasted directly from the documentation here: https://github.com/PickNikRobotics/abb_ros2/blob/rolling/docs/README.md#simulating-a-robot-in-ros-2

**Comment by Yadunund** [comment]
So there are a few breaking changes between `humble` and `iron` and `rolling` binaries of `ros2_controllers`. I only tested with Iron and Rolling. I plan to fix the CI job in this repo later this week so I can investigate this further then. Maybe the workaround is to create a `humble` branch off the latest working commit.

**Comment by Yadunund** [comment]
Hi @jodle001 

I think I found the issue. Could you try this PR https://github.com/PickNikRobotics/abb_ros2/pull/60?

I realized when I tested the commit that "broke" things, I had tested with a moveit config for a different robot which had the `moveit_controllers.yaml` file properly setup.
