### ISSUE TITLE
Controller failed during execution

### ISSUE THREAD

**Issue by WhittemoreChou** [PickNikRobotics/abb_ros2#64]
Hi, I was trying to go through the simulation instructions, but it failed to move the robot. I've tried to install moveit from binary and source, but neither of them worked.

**I'm using:**
- Ubuntu 22.04 Jammy
- ROS Humble 
- Moveit Humble
- Humble branch of this repo

### Before "Plan & Execute"
The controllers were launched properly, and the robot is visible, but some error occured in the terminal launching moveit. Some snippets in the **moveit terminal**:
`[move_group-1] [ERROR] [1712989408.783870240] [moveit.ros.occupancy_map_monitor.middleware_handle]: No 3D sensor plugin(s) defined for octomap updates
[move_group-1] [INFO] [1712989408.786487167] [moveit.ros_planning_interface.moveit_cpp]: Loading planning pipeline 'move_group'
[move_group-1] [INFO] [1712989408.800953160] [moveit.ros_planning.planning_pipeline]: Using planning interface 'OMPL'
[move_group-1] [ERROR] [1712989408.802300586] [moveit.ros_planning.planning_pipeline]: Exception while loading planning adapter plugin 'default_planner_request_adapters/AddTimeParameterization': According to the loaded plugin descriptions the class default_planner_request_adapters/AddTimeParameterization with base class type planning_request_adapter::PlanningRequestAdapter does not exist. Declared types are  default_planner_request_adapters/AddRuckigTrajectorySmoothing default_planner_request_adapters/AddTimeOptimalParameterization default_planner_request_adapters/Empty default_planner_request_adapters/FixStartStateBounds default_planner_request_adapters/FixStartStateCollision default_planner_request_adapters/FixStartStatePathConstraints default_planner_request_adapters/FixWorkspaceBounds default_planner_request_adapters/ResolveConstraintFrames`

`[rviz2-2] Warning: class_loader.impl: SEVERE WARNING!!! A namespace collision has occurred with plugin factory for class rviz_default_plugins::displays::InteractiveMarkerDisplay. New factory will OVERWRITE existing one. This situation occurs when libraries containing plugins are directly linked against an executable (the one running right now generating this message). Please separate plugins out into their own library or just don't link against the library and use either class_loader::ClassLoader/MultiLibraryClassLoader to open.
[rviz2-2]          at line 253 in /opt/ros/humble/include/class_loader/class_loader/class_loader_core.hpp
[rviz2-2] [ERROR] [1712989412.290795067] [moveit_ros_visualization.motion_planning_frame]: Action server: /recognize_objects not available
[rviz2-2] [INFO] [1712989412.309354962] [moveit_ros_visualization.motion_planning_frame]: MoveGroup namespace changed: / -> . Reloading params.
[rviz2-2] Error:   Name of virtual joint is not specified
[rviz2-2]          at line 77 in ./src/model.cpp`

### After"Plan & Execute"
In the **moveit terminal**:
`[move_group-1] [INFO] [1712990535.023803560] [moveit.simple_controller_manager.follow_joint_trajectory_controller_handle]: joint_trajectory_controller started execution
[move_group-1] [WARN] [1712990535.023870835] [moveit.simple_controller_manager.follow_joint_trajectory_controller_handle]: Goal request rejected
[move_group-1] [ERROR] [1712990535.023905674] [moveit.simple_controller_manager.follow_joint_trajectory_controller_handle]: Goal was rejected by server
[move_group-1] [ERROR] [1712990535.024029339] [moveit_ros.trajectory_execution_manager]: Failed to send trajectory part 1 of 1 to controller joint_trajectory_controller
[move_group-1] [INFO] [1712990535.024042082] [moveit_ros.trajectory_execution_manager]: Completed trajectory execution with status ABORTED ...
[move_group-1] [INFO] [1712990535.031561068] [moveit_move_group_default_capabilities.move_action_capability]: Solution found but controller failed during execution
[rviz2-2] [INFO] [1712990535.033060957] [move_group_interface]: Plan and Execute request aborted
[rviz2-2] [ERROR] [1712990535.033182323] [move_group_interface]: MoveGroupInterface::move() failed or timeout reached`

In the **controller terminal**:
`[ros2_control_node-1] [INFO] [1712990535.023239545] [joint_trajectory_controller]: Received new action goal
[ros2_control_node-1] [ERROR] [1712990535.023350523] [joint_trajectory_controller]: Time between points 0 and 1 is not strictly increasing, it is 0.000000 and 0.000000 respectively`

**Comment by Yadunund** [comment]
> ERROR] [1712989408.802300586] [moveit.ros_planning.planning_pipeline]: Exception while loading planning adapter plugin 'default_planner_request_adapters/AddTimeParameterization': According to the loaded plugin descriptions the class default_planner_request_adapters/AddTimeParameterization with base class type planning_request_adapter::PlanningRequestAdapter does not exist. Declared types are  default_planner_request_adapters/AddRuckigTrajectorySmoothing default_planner_request_adapters/AddTimeOptimalParameterization default_planner_request_adapters/Empty default_planner_request_adapters/FixStartStateBounds default_planner_request_adapters/FixStartStateCollision default_planner_request_adapters/FixStartStatePathConstraints default_planner_request_adapters/FixWorkspaceBounds default_planner_request_adapters/ResolveConstraintFrames


Are you using `moveit2` humble binaries? What is the version of your binaries?

Afiak `moveit2` renamed `default_planner_request_adapters/AddTimeParameterization` to `default_planner_request_adapters/AddTimeOptimalParameterization` for their `2.7.x` release but humble binaries are still `2.5.x` 

That was the reason for this PR https://github.com/PickNikRobotics/abb_ros2/pull/55

**Comment by WhittemoreChou** [comment]
> Are you using `moveit2` humble binaries? What is the version of your binaries?
> 
> Afiak `moveit2` renamed `default_planner_request_adapters/AddTimeParameterization` to `default_planner_request_adapters/AddTimeOptimalParameterization` for their `2.7.x` release but humble binaries are still `2.5.x`
> 
> That was the reason for this PR #55

Yes, I'm using `moveit2` humble binaries `2.5.5`. And I've tried to build `moveit2` from source files in their humble branch, same errors.

**Comment by Yadunund** [comment]
Ah interesting, it looks like the  "breaking" change was also backported to `humble` https://github.com/ros-planning/moveit2/pull/2170 in upsteam moveit2 and is hence part of the `2.5.5`.

I can backport #55 to the humble branch here.
